/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appli_etudiants.formulaire;

import appli_etudiants.CV_element.Cv_photo;
import appli_etudiants.DaoS4;
import appli_etudiants.Etudiants;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author verod_000
 */
public class PanneauPhoto extends javax.swing.JDialog {

    JFileChooser choixPhoto = null;
    ImageIcon lImage = null;
    private Etudiants etudiantPhoto;
    /**
     * Creates new form PanneauPhoto
     *
     * @param parent
     * @param modal
     * @param etudiant
     * @throws java.sql.SQLException
     */
    public PanneauPhoto(java.awt.Frame parent, boolean modal, Etudiants etudiant) throws SQLException {
        super(parent, modal);
        initComponents();
        etudiantPhoto = etudiant;
        ImageIcon photoTest = new ImageIcon(DaoS4.getPhoto());
        jLabelPhoto.getGraphics().drawImage(photoTest.getImage(),0,0, 94, 94, null);
        jLabelPhoto.setIcon(photoTest);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelPhoto = new javax.swing.JLabel();
        jButtonChoixPhoto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonChoixPhoto.setText("sélectionnez votre photo");
        jButtonChoixPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChoixPhotoActionPerformed(evt);
            }
        });

        jLabel2.setText("Votre Photo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel1))
                            .addComponent(jLabelPhoto)
                            .addComponent(jButtonChoixPhoto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel2)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonChoixPhoto)
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPhoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChoixPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChoixPhotoActionPerformed
        if (choixPhoto == null) {
            choixPhoto = new JFileChooser(".");
            choixPhoto.setFileFilter(new FileNameExtensionFilter("Images", "jpg", "png"));
        }
        choixPhoto.setCurrentDirectory(choixPhoto.getCurrentDirectory());
        choixPhoto.showOpenDialog(null);
        if (choixPhoto.getSelectedFile() == null) {
            choixPhoto = null;
        } else {
            try {
                this.lImage = new ImageIcon(choixPhoto.getSelectedFile().toString());
                
                jLabelPhoto.getGraphics().drawImage(this.lImage.getImage(),0,0, 94, 94, null);
                jLabelPhoto.setIcon(lImage);
                Cv_photo newPhoto = new Cv_photo();
                newPhoto.setEtudiant(this.etudiantPhoto);
                newPhoto.setPhoto(choixPhoto.getSelectedFile().toString());
                DaoS4.photoDao().createOrUpdate(newPhoto);
            } catch (SQLException ex) {
                Logger.getLogger(PanneauPhoto.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }

    }//GEN-LAST:event_jButtonChoixPhotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanneauPhoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanneauPhoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanneauPhoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanneauPhoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    PanneauPhoto dialog = new PanneauPhoto(new javax.swing.JFrame(), true, new Etudiants());
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PanneauPhoto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChoixPhoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPhoto;
    // End of variables declaration//GEN-END:variables
}
